name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Thiết lập Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cài đặt dependencies backend
        run: |
          cd backend
          npm install

      - name: Chạy test backend
        run: |
          cd backend
          npm test || echo "Không có test hoặc test thất bại"

      - name: Cài đặt dependencies frontend
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Thêm bước deploy nếu cần thiết 