name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Thiết lập Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cài đặt dependencies backend
        run: |
          cd backend
          npm install

      - name: Chạy test backend
        run: |
          cd backend
          npm test || echo "Không có test hoặc test thất bại"

      - name: Cài đặt dependencies frontend
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy lên server qua SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/ubuntu/app
            git pull origin main
            npm install --production
            npm run build || true
            pm2 restart all || pm2 start index.js 

            
